apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  application.properties: |
    server.port=8085

    spring.datasource.url=jdbc:postgresql://postgres:5432/orders
    spring.datasource.driver-class-name=org.postgresql.Driver

    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    eureka.client.service-url.default-zone=http://eureka-server:8761/eureka/
    spring.application.name=orders

    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
