apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketmanagement-service-config
data:
  application.properties: |
    server.port=8090

    spring.datasource.url=jdbc:postgresql://postgres:5432/ticketmanagement
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=admin
    spring.datasource.password=postgres123
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    eureka.client.service-url.default-zone=http://localhost:8761/eureka/
    spring.application.name=ticketManagement

    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=user
    spring.rabbitmq.password=123
