apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: general-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /carts
            pathType: Prefix
            backend:
              service:
                name: cart
                port:
                  number: 8081
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: events
                port:
                  number: 8095
          - path: /fileGeneration
            pathType: Prefix
            backend:
              service:
                name: file-generation
                port:
                  number: 8083
          - path: /notifications
            pathType: Prefix
            backend:
              service:
                name: notifications
                port:
                  number: 8084
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 8085
          - path: /organizations
            pathType: Prefix
            backend:
              service:
                name: organizations
                port:
                  number: 8086
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payments
                port:
                  number: 8087
          - path: /refunds
            pathType: Prefix
            backend:
              service:
                name: refunds
                port:
                  number: 8088
          - path: /reviews
            pathType: Prefix
            backend:
              service:
                name: reviews
                port:
                  number: 8089
          - path: /ticketManagement
            pathType: Prefix
            backend:
              service:
                name: ticket-management
                port:
                  number: 8090
          - path: /tickets
            pathType: Prefix
            backend:
              service:
                name: tickets
                port:
                  number: 8091
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 8092
          - path: /venues
            pathType: Prefix
            backend:
              service:
                name: venues
                port:
                  number: 8093