apiVersion: v1
kind: ConfigMap
metadata:
  name: events-config
data:
  application.properties: |
    server.port=8095
    spring.datasource.url=jdbc:postgresql://postgres:5432/events
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    eureka.client.service-url.default-zone=http://eureka-server:8761/eureka/
    spring.application.name=events
    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
    
