apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-generation-deployment
  labels:
    app: file-generation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-generation
  template:
    metadata:
      labels:
        app: file-generation
    spec:
      containers:
        - name: file-generation
          image: duarte15sousa/evently_file_generation
          ports:
            - containerPort: 8083