apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  application.properties: |
    server.port=8092

    spring.datasource.url=jdbc:postgresql://postgres:5432/users
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=admin
    spring.datasource.password=postgres123
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    eureka.client.service-url.default-zone=http://localhost:8761/eureka/
    spring.application.name=users

    spring.security.user.password=disabled
    jwt.secret=MINHA_SUPER_SECRET_KEY_123456789
    jwt.expiration=3600000
