apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  application.properties: |
    server.port=8092

    spring.datasource.url=jdbc:postgresql://postgres:5432/users
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    spring.application.name=users

    spring.security.user.password=disabled
    jwt.secret=MINHA_SUPER_SECRET_KEY_123456789
    jwt.expiration=3600000

    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    eureka.instance.prefer-ip-address=true
