apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  application.properties: |
    server.port=8084

    spring.datasource.url=jdbc:postgresql://postgres:5432/notifications
    spring.datasource.driver-class-name=org.postgresql.Driver

    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    eureka.client.service-url.default-zone=http://eureka-server:8761/eureka/
    spring.application.name=notifications

    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672

    # ==== CONFIG EMAIL ====
    spring.mail.host=smtp.gmail.com
    spring.mail.port=587
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
