apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.properties: |
    server.port=8080
    logging.level.org.springframework.cloud.gateway=debug
    logging.level.reactor.netty.http.client=debug
    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    spring.application.name=ApiGateway
    spring.main.web-application-type=reactive
    spring.main.allow-bean-definition-overriding=true
    spring.cloud.gateway.discovery.locator.enabled=true
