apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
  labels:
    app: reviews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: duarte15sousa/evently_reviews
          ports:
            - containerPort: 8089