apiVersion: v1
kind: ConfigMap
metadata:
  name: reviews-config
data:
  application.properties: |
    server.port=8089

    spring.datasource.url=jdbc:postgresql://postgres:5432/reviews
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=admin
    spring.datasource.password=postgres123
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    eureka.client.service-url.default-zone=http://eureka-server:8761/eureka/
    spring.application.name=reviews
