apiVersion: v1
kind: ConfigMap
metadata:
  name: filegeneration-service-config
data:
  application.properties: |
    server.port=8083
    spring.security.user.password=disabled
    jwt.secret=MINHA_SUPER_SECRET_KEY_123456789
    jwt.expiration=3600000
    eureka.client.service-url.default-zone=http://localhost:8761/eureka/
    spring.application.name=fileGeneration

    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=user
    spring.rabbitmq.password=123
