apiVersion: v1
kind: ConfigMap
metadata:
  name: file-generation-config
data:
  application.properties: |
    server.port=8083
    spring.security.user.password=disabled
    jwt.secret=MINHA_SUPER_SECRET_KEY_123456789
    jwt.expiration=3600000
    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    spring.application.name=fileGeneration
    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    eureka.instance.prefer-ip-address=true
