apiVersion: apps/v1
kind: Deployment
metadata:
  name: venues-deployment
  labels:
    app: venues
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: venues
  template:
    metadata:
      labels:
        app: venues
    spec:
      containers:
        - name: venues
          image: duarte15sousa/evently_venues
          ports:
            - containerPort: 8093
          volumeMounts:
            - name: config-volume
              mountPath: /config
#          resources:
#            requests:
#              memory: "256Mi"
#              cpu: "250m"
#            limits:
#              memory: "512Mi"
#              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8093
            initialDelaySeconds: 70
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8093
            initialDelaySeconds: 70
            periodSeconds: 20
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
      volumes:
        - name: config-volume
          configMap:
            name: venues-config