apiVersion: v1
kind: ConfigMap
metadata:
  name: organizations-config
data:
  application.properties: |
    server.port=8086

    spring.datasource.url=jdbc:postgresql://postgres:5432/organizations
    spring.datasource.driver-class-name=org.postgresql.Driver

    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672

    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    spring.application.name=organizations

    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    eureka.instance.prefer-ip-address=true
    spring.main.lazy-initialization=true
