apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
data:
  application.properties: |
    server.port=8087

    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    spring.application.name=payments

    spring.datasource.url=jdbc:postgresql://postgres:5432/payments
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=admin
    spring.datasource.password=postgres123

    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672

    # nomes das filas / exchanges
    app.payments.exchange=payments_exchange
    app.payments.routing-key=payments
    app.payments.queue=payments_queue

    # Refund events (consumidos pelo Payments)
    app.refunds.exchange=refunds.exchange
    app.refunds.queue=payments.refunds.queue
    app.refunds.routing-key=refund.*

    # PayPal sandbox
    paypal.base-url=https://api-m.sandbox.paypal.com

    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    eureka.instance.prefer-ip-address=true

    eureka.client.enabled=false
    eureka.client.register-with-eureka=false
    eureka.client.fetch-registry=false
    spring.cloud.discovery.enabled=false
