apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
type: Opaque
stringData:
  paypal-client-id: "AXg38Wc0yftQGtEHmRqep8aAYSB_vH2WFjTV7bFbQ0cXhot6KZsbC4AQLxccwJgCWaT0EcFi3cMHu5Fq"
  paypal-client-secret: "EMcwWsJkqmelzHE-nqHo4IL8Ndjib9yzQLg9V1mm3maP6t7vu7HgHBT6QwvGAZwgiz29XosMcBPf1H05"